// <auto-generated />
namespace Microsoft.CodeAnalysis.Razor.Workspaces
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.CodeAnalysis.Razor.Workspaces.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Value cannot be null or empty.
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty
        {
            get => GetString("ArgumentCannotBeNullOrEmpty");
        }

        /// <summary>
        /// Value cannot be null or empty.
        /// </summary>
        internal static string FormatArgumentCannotBeNullOrEmpty()
            => GetString("ArgumentCannotBeNullOrEmpty");

        /// <summary>
        /// The method {0} should only be called from the foreground thread.
        /// </summary>
        internal static string InvalidThreading_ForegroundThreadRequired
        {
            get => GetString("InvalidThreading_ForegroundThreadRequired");
        }

        /// <summary>
        /// The method {0} should only be called from the foreground thread.
        /// </summary>
        internal static string FormatInvalidThreading_ForegroundThreadRequired(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("InvalidThreading_ForegroundThreadRequired"), p0);

        /// <summary>
        /// The method {0} should only be called from a background thread.
        /// </summary>
        internal static string InvalidThreading_BackgroundThreadRequired
        {
            get => GetString("InvalidThreading_BackgroundThreadRequired");
        }

        /// <summary>
        /// The method {0} should only be called from a background thread.
        /// </summary>
        internal static string FormatInvalidThreading_BackgroundThreadRequired(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("InvalidThreading_BackgroundThreadRequired"), p0);

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
